#!/bin/bash

conn="Grizznet-Secure"

echo "To figure out what is your wifi interface name use: "iw dev", "ip link", or "ifconfig" Ex: wlp0s20f3"
read -p "Provide interface name: " ifname
read -p "Provide your email! Ex: yourname@oakland.edu: " email
read -p "Provide your netid password: " -s pass

command="sudo nmcli connection add type wifi con-name $conn"

nmcli connection show $conn &> /dev/null

if [ $? -eq 0 ]; then
    command="sudo nmcli connection modify $conn"
fi

$command \
    connection.interface-name $ifname \
    ssid $conn \
    wifi-sec.key-mgmt wpa-eap \
    802-1x.eap peap \
    802-1x.identity $email \
    802-1x.password $pass \
    802-1x.phase2-auth mschapv2 \
    802-1x.ca-cert "/etc/ssl/certs/ca-certificates.crt" \
    802-1x.anonymous-identity ""
